- src/main/java/com/sejong/sejongpeer/domain/common/BaseAuditEntity.java
- src/main/java/com/sejong/sejongpeer/domain/common/BaseEntity.java
- close #13 
- BaseEntity에는 createdAt, BaseAuditEntity에는 updatedAt으로
- 엔티티 클래스에 BaseAuditEntity 상속받을 시 createdAt, updatedAt 자동 생성
- 
-
> :sparkles: feat: BaseEntity 추가

- src/main/java/com/sejong/sejongpeer/domain/college/api/CollegeMajorController.java
- src/main/java/com/sejong/sejongpeer/domain/college/dto/CollegeMajorResponse.java
- src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeMajor.java
- src/main/java/com/sejong/sejongpeer/domain/college/repository/CollegeMajorRepository.java
- src/main/java/com/sejong/sejongpeer/domain/college/service/CollegeMajorService.java
- src/test/java/com/sejong/sejongpeer/domain/college/repository/CollegeMajorRepositoryTest.java
- close #18 
- 단과대 목록을 가져오는 기능을 구현했습니다.
- 단과대 이름을 파라미터로 소속된 학과과 목록을 가져오는 기능을 구현했습니다.
- 학교 공지사항의 개설 과목 엑셀파일을 참고하여 college-major-relations 테이블에 단과대 - 학과 정보를 넣었습니다.
> :sparkles: CollegeMajor 앤티티 생성 & 조회 기능 추가

- src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
- src/main/java/com/sejong/sejongpeer/domain/member/dto/request/AccountFindRequest.java
- src/main/java/com/sejong/sejongpeer/domain/member/dto/request/MemberUpdateRequest.java
- src/main/java/com/sejong/sejongpeer/domain/member/dto/response/AccountFindResponse.java
- src/main/java/com/sejong/sejongpeer/domain/member/dto/response/ExistsCheckResponse.java
- src/main/java/com/sejong/sejongpeer/domain/member/dto/response/NicknameCheckResponse.java
- src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
- src/main/java/com/sejong/sejongpeer/domain/member/entity/type/MemberInfo.java
- src/main/java/com/sejong/sejongpeer/domain/member/repository/MemberRepository.java
- src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
- src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
- src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
- src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java
- src/main/resources/application-dev.yml
- src/test/java/com/sejong/sejongpeer/domain/member/service/MemberServiceTest.java
- #42
- 휴대폰번호, 카카오 계정 중복체크 추가했습니다.
- 휴대폰번호 정규식 버그 수정했습니다.
- accessToken이 유효한데도 `SecurityContextHolder`에 저장되지 않던 버그 수정하였습니다.
- 현재 service 하나에 메소드가 너무 많이 몰려 추후에 리팩토링이 필요할 것 같습니다.  서비스를 분리하거나 고수준 - 저수준으로 나누거나 해야할 것 같습니다.
- 회원정보 수정 시, 각 분기에 대해 strategy 패턴을 쓰기엔 strategy가 repository에 의존하게 되어서 enum으로 관리하는 방법을 선택했습니다. 좋은 방법인지는 잘 모르겠습니다..
-
> 🐛 회원정보 수정 기능 fix

- src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
- close #77 
- findTargetBuddy 메소드에서 getPartner를 통해 항상 partner 필드의 buddy를 반환하는 문제에 대한 수정
- 
-
> 🐛 짝매칭 성사가 되었을 때 BuddyMatched 엔티티에서 target Buddy만을 받아오는 문제 해결

- src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/CompletedPartnerInfoResponse.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/MatchingPartnerInfoResponse.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/PartnerInfoResponse.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
- src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
- #73 
- 버디 매칭 후 상대방 정보 요청
- 버디 매칭 수락 완료 후 상대방 정보 요청
- BuddyMatchingService에 findTargetBuddy 공통으로 쓰이는 함수 리펙토링
- BuddyService에서 BuddyMatchingServiced의 함수를 쓰려고
- '''private final MatchingService matchingService;
private final BuddyRepository buddyRepository;
private final MemberRepository memberRepository;
private final BuddyMatchingService buddyMatchingService;''' 이런식으로 
buddyService에서 BuddyMatchingService를 불러와서 사용을 했는데 더 좋은 방법이 있을까요,,?  
찾아보니 나중에 서로 참조를 하게 되는 경우가 생기면 순환참조 문제가 발생할 수 있다고 하긴하는데 다른 방법을 찾지못해서 여쭤봅니다!
-
> ✨ Buddy, BuddyMatched가 Complete일 때 응답 메소드 구현

- src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
- src/main/java/com/sejong/sejongpeer/domain/honbab/dto/response/MatchingPartnerInfoResponse.java
- src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabMatchedRepository.java
- src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabRepository.java
- src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
- src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
- src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
- close #80 
- 피그마 상에서 이전의 버디 매칭과 달리 프론트분들께 받는 거절/수락 기능이 없기 때문에 혼밥 매칭 상대를 찾았을 경우 바로 상대 정보를 반환합니다.
- 버디 선후배 짝매칭 성공 시 발송되는 문자 내용 추가로 수정했습니다.
-
> ✨ 혼밥 짝꿍 매칭 성공 시 상대방 정보 제공

- src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
- close #106 
- 버디를 찾았으나 등록된 버디가 없다는 response에 대한 수정
- 
-
> 🐛 유저의 버디 엔티티를 찾을 때 찾는 상태를 FOUNDED_BUDDY로 변경

- src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/Buddy.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddymatched/BuddyMatched.java
- src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/Honbab.java
- src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbabmatched/HonbabMatched.java
- src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
- #110 
- cascade 옵션과 orphanRemoval을 사용해, member 삭제시 연관된 엔티티가 전부 삭제되도록 수정하였습니다.
- buddyMatched, honbabMatched의 상대편 buddy, honbab 신청내역도 삭제되는 로직입니다. 추후 문제가 있다고 판단되면 다른 방식으로 상대편의 상태를 변경하는 로직으로 변경해야 할 것 같습니다.
- 
-
> :bug: 회원탈퇴 버그 수정

- src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/type/HonbabStatus.java
- src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
- close #123 
- 프론트에서 매칭 페이지로 넘어가는 조건에 null, time out 뿐만 아니라 expired 상태 추가해주시면 될 것 같습니다 
- postman으로 테스트 완료하였고 matching completed이후 15분 지났을 경우 상태 체크 api에서 expired를 반환합니다
-
> ✨ 혼밥 매칭 후 재신청 가능한 상태 추가 및 상태 체크 시 업데이트

- src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
- close #135 
- 최종적인 컨트롤러의 response를 List 형식의 반환으로 수정했습니다
- 서로 다른 유저 두 명 모두가 모두 수락을 한 이후 호출되는 api라는 점을 고려해서 buddyRepository에서 한 유저에 대해 MATCHING_COMPLETED인 Buddy를 모두 찾아 list에 저장하고 
- 특정 유저의 위에서 언급한 list 내 각 버디에 대해 buddyMatchedRepository로 BuddyMatched를 찾아
- 위의 BuddyMatched에서 partner(otherBuddy)의 정보를 반환하는 로직입니다
- postman으로 DB에 계정 추가해서 매칭 된 버디가 한 명뿐일 때와 여러명일 때 모두 상대 유저 정보 response 확인했습니다.
-
> ✨ 버디 양쪽 모두 매칭 수락 이후 모든 상대 정보 반환 기능 추가

- src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/type/BuddyStatus.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
- close #148
- 버디 상태값  REATIVATE 추가
- 버디 상태값 반환 메소드에서 REJECT된 버디의 패널티 처리
- 
-
> 🐛 REJECT상태인 버디 등록 시 상태값 반환에서 처리

- src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/MatchingStatusResponse.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
- close #157
- 버디 상태값 요청 응답값에 요청 유저의 Buddy 상태값이 MATCHING_COMPLTED인 count를 포함하여 리턴
- 
-
> ♻️ 버디 상태값 요청에 MATCHING_COMPLETED 된 count 같이 넘겨주도록 변경

- src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyMatchingController.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/scheduler/MatchingScheduler.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
- src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
- close #149 
- 기존 버디 수락/거절 메소드를 공동으로 사용하기 위해 BuddyMatchingService 리팩토링
- 스케쥴러 방식으로 구현
- 자동으로 거절된 유저와 거절 당한 유저에게 서로 다른 문자 내용을 발송
- 
-
> ✨ 24시간 이내 버디 수락/거절 미응답 시 자동 거절 처리 스케쥴러 구현 및 문자 발송 기능 구현

- src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
- src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
- close #162 
- 버디 수락/거절 로직에서 로그인한 유저의 버디를 이용하여 BuddyMatched를 찾는 방식을 repository를 사용하지 않는 방식으로 변경
- 버디 다 회 신청 가능해지면서 매칭된 모든 상대 유저 정보 반환하는 부분에서도 Buddy로부터 BuddyMatched를 찾을 때 동일한 방식으로 변경
- 기능적으로 문제 없음을 확인했습니다
-
> ♻️ Buddy에서 BuddyMatched 찾는 방식 쿼리문 줄이도록 리팩토링

- src/main/java/com/sejong/sejongpeer/domain/externalactivitystudy/repository/ExternalActivityStudyRepository.java
- src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/Lecture.java
- src/main/java/com/sejong/sejongpeer/domain/lecturestudy/repository/LectureStudyRepository.java
- src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyPostSearchRequest.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudySearchRequest.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
- src/main/java/com/sejong/sejongpeer/domain/study/repository/StudyRepository.java
- src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
- src/main/java/com/sejong/sejongpeer/domain/study/service/StudySpecification.java
- src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
- close #189 
- 6개월 단위의 전체 게시글 무한 스크롤 기능 구현
- 게시글 상세 조회(글쓴이 전공, 닉네임 등 포함)
- 게시글 다중 조건 검색 
- Lecture 엔티티가 BaseEntity를 상속 받고 있어 "0000-00-00 00:..." 이렇게 초기화가 되어  created_at 칼럼이 추가가 되었는데 이 부분이 jpa mapping 오류(500 error)를 유발하고 실제 필요가 없는 칼럼이므로 삭제
-
> ✨스터디 게시글 무한 스크롤 전체 조회, 단건 상세 조회, 게시글 다중 조건 검색 API

- src/main/java/com/sejong/sejongpeer/domain/externalactivity/controller/ExternalActivityController.java
- src/main/java/com/sejong/sejongpeer/domain/externalactivity/dto/ExternalActivityCategoryResponse.java
- src/main/java/com/sejong/sejongpeer/domain/externalactivity/service/ExternalActivityService.java
- close #215 
- 교외 활동 스터디 게시글 생성 시 필요한 external_activity_id request를 위한 교외 활동 카테고리 전체 정보 조회 API
- 포스트맨 200 ok 확인
- API 명세서(NEW) 페이지에 request, reponse 작성 완료
> ✨ 교외 활동 카테고리 유형 정보 조회

- src/main/java/com/sejong/sejongpeer/domain/externalactivity/entity/ExternalActivity.java
- src/main/java/com/sejong/sejongpeer/domain/study/api/ExternalActivityStudyController.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
- src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
- src/main/java/com/sejong/sejongpeer/domain/study/entity/type/Frequency.java
- src/main/java/com/sejong/sejongpeer/domain/study/entity/type/StudyMethod.java
- src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
- src/main/java/com/sejong/sejongpeer/domain/study/vo/StudyVo.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
- close #
- 게시글 생성 API
- Request값 불필요한 값 삭제 및 추가
- lecture 엔티티에 BaseEntity로 생성 시간 나타나는 것 삭제
- Study에 현재 참여인원 추가, 모집빈도 Enum 추가, 스터디 방식 추가
- 
- 태그 기능은 아직 구현 못했습니다.
> 게시글 생성 API, Study 엔티티 밑 request 수정

- src/main/java/com/sejong/sejongpeer/domain/study/api/LectureStudyController.java
- src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
- src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java
- src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
- src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
- close #217 
- 외래키 제약 조건 고려
- 하나의 컨트롤러로 교내 및 교외 스터디 게시글 관련 튜플 모두 삭제
- 게시글 작성자만 삭제 가능하도록 예외 처리 완료
- 프론트에서 존재하지 않는 스터디 id로 요청 시 예외 처리 완료
- 
-
> ✨ 교내외 스터디 게시글 단건 삭제 

- build.gradle
- src/main/java/com/sejong/sejongpeer/domain/image/api/ImageController.java
- src/main/java/com/sejong/sejongpeer/domain/image/dto/request/StudyImageUploadRequest.java
- src/main/java/com/sejong/sejongpeer/domain/image/dto/response/StudyImageUrlResponse.java
- src/main/java/com/sejong/sejongpeer/domain/image/entity/Image.java
- src/main/java/com/sejong/sejongpeer/domain/image/service/ImageService.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
- src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
- src/main/java/com/sejong/sejongpeer/infra/config/aws/S3Config.java
- close #230 
- 여러 개의 파일을 한번에 업로드 구현 완료
- 프론트에서 List<String> 형식으로 base64 string 인코딩된 이미지를 request로 받음
- 백에서 이 이미지를 디코딩해서 이미지 파일로 변환하여 S3에 업로드 및 DB에 URL 저장
- 게시글 상세 조회 시 study 테이블의 img_url 칼럼이 아니라 스터디와 이미지 일대다 관계로 새롭게 정의한 이미지 테이블에서 List 형식으로 이미지 아이디와 함께 반환하도록 로직 수정
- 급하게 구현했기 때문에 추후 코드 리펙토링 예정
- 200 ok 이미지 업로드 및 게시글 상세 조회 api 확인 완료
> ✨ 스터디 게시글 이미지 base64 string 처리 및 병렬 S3 업로드, 상세 조회 시 이미지 반환 로직 수정

- src/main/java/com/sejong/sejongpeer/domain/member/repository/MemberRepository.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyMatchingRequest.java
- src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/dto/request/StudyMatchingRequest.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
- src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
- close #231 
- studyRelation 엔티티의 status 변경 
- 지원자의 닉네임에 대한 예외 처리 완료
- 스터디 게시글과 지원자의 지원 이력에 대한 예외 처리 완료 
- 수락 시 현재 스터디 참여 인원++ 처리 완료
- 
- postman 200 ok 및 DB status 변경 내역 확인 완료
- 수락 처리된 스터디 게시글 participants_count++ 확인 완료
> ✨ 스터디 지원자에 대한 수락/거절 상태 변경 및 수락일 경우 참여 인원 증가 처리 API

- src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
- src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
- close #246 
- 기존 accept된 지원자를 나타내는 변수명이 프론트 입장에서 모호한 것 같아 수정
- 참여 인원 로직 -> count 추가 쿼리 나가지 않도록 로직 수정
- 스터디 게시글 생성 시 request로 받는 모집 전체 인원을 게시글 상세 조회 response에서도 추가 반환
- 
- 200 ok 확인
> ✨ 게시글 상세 조회 스터디 모집 인원 및 가입된 인원 수 

- src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/entity/StudyRelation.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/entity/type/StudyMatchingStatus.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
- src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
- close #251 
- 스터디 지원 취소
- 지원 취소 시, 같은 스터디 지원 1시간 제한 패널티 부여
- 마이페이지 내가 지원한 스터디 API 로직에서 스터디 지원을 취소하지 않은 게시글만 반환하도록 로직 수정
- 
- 스터디 지원 관련 예외 처리까지 모두 확인 : 중복 지원 409, 스터디 취소 후 재지원 패널티 403
> ✨ 스터디 지원 취소 및 패널티 부여

- src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
- src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
- close #257 
- 500 error 해결
- 
- 스터디 첫 지원 -> 지원 취소 -> 재지원 시 패널티 로직 200 ok 확인
- 스터디 첫 지원 -> 재지원 -> 중복 지원 예외 처리 확인
- 스터디 지원 -> 취소 시 발생하는 500 에러 해결 수 200 ok 확인
> 🐛 스터디 지원 취소 및 재지원 로직 수정

- src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
- close #271 
- 게시글에 이미지가 있다면 hasImage가 true
- 피그마 게시글 목록 무한스크롤 조회 시 제목 옆 이미지 포함 여부에 따른 그림 아이콘 여부에 해당하는 data
- 
- 백엔드는 세종스터디 전체 기능 구현 완료
> 🐛 StudyTatalPostResopnse hasImage 게시글 이미지 포함 여부 로직 수정

- src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyApplicantsListRespone.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
- close #287 
- 마이페이지 자신이 작성한 스터디 게시글 지원자 목록 조회에서 게시글 모집 상태와 지원자 매칭 상태 data 추가 및 이를 위한 로직 변경 
- 
-
> ✨ 스터디 게시글 별 모집 상태 및 지원자 매칭 상태 반환 추가

- src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
- src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
- src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
- close #316 
아래 4가지 상황에 대한 문자 발송 내용 및 로직 수정 후 모두 200 ok 확인 완료
1. 스터디 지원자 있을 경우 게시글 작성자한테
2. 스터디 게시글이 삭제되었을 경우 지원자한테
3. 스터디 모집 마감되었을 경우 지원자한테
4. 스터디 지원 거절되었을 경우 거절된 지원자한테
- 
-
> ♻️ 세종스터디 문자 메세지 최종

- src/main/java/com/sejong/sejongpeer/domain/image/service/ImageService.java
- src/main/java/com/sejong/sejongpeer/domain/study/api/ExternalActivityStudyController.java
- src/main/java/com/sejong/sejongpeer/domain/study/api/LectureStudyController.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
- src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyCreateResponse.java
- src/main/java/com/sejong/sejongpeer/domain/study/service/ExternalActivityStudyService.java
- src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java
- src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
- close #360 
- 교내 수업 스터디 생성 + 해당 게시글 이미지 업로드 통합
- 교외 수업 스터디 생성 + 해당 게시글 이미지 업로드 통합
- 이미지 용량 문제로 413 상태코드 뜰 경우 게시글 정보를 DB에 저장하지 않음
- 
-
> ♻️ 교내 및 교외 스터디 게시글 작성 API를 각각 게시글 이미지 업로드 API와 통합
