SejongPeer/SejongPeer-back

build.gradle
src/main/java/com/sejong/sejongpeer/global/common/constants/EnvironmentConstants.java
src/main/java/com/sejong/sejongpeer/global/common/response/GlobalResponse.java
src/main/java/com/sejong/sejongpeer/global/common/response/GlobalResponseAdvice.java
src/main/java/com/sejong/sejongpeer/global/error/ErrorResponse.java
src/main/java/com/sejong/sejongpeer/global/error/GlobalExceptionHandler.java
src/main/java/com/sejong/sejongpeer/global/error/exception/CustomException.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
src/main/java/com/sejong/sejongpeer/global/util/SpringEnvironmentUtil.java

- close #7
- 전역 처리를 위한 RestControllerAdvice 추가
- 코드 환경 처리를 위한 SpringEnvironmentUtil 추가로 prod환경 따로, dev 따로 분리 처리가 가능
- 
-

:safety_vest: chore: 전역 처리를 위한 RestControllerAdvice 추가

---

build.gradle
src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
src/main/java/com/sejong/sejongpeer/global/config/swagger/SwaggerConfig.java
src/main/resources/application.yml

- close #12
- SwaggerConfig 추가
- 
-

:memo: chore: SwaggerConfig 추가

---

src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
src/main/java/com/sejong/sejongpeer/domain/auth/dto/response/SignInResponse.java
src/main/java/com/sejong/sejongpeer/domain/auth/entity/RefreshToken.java
src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
src/main/java/com/sejong/sejongpeer/domain/auth/service/JwtService.java
src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
src/main/java/com/sejong/sejongpeer/global/util/CookieUtil.java
src/main/java/com/sejong/sejongpeer/security/MemberDetails.java
src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
src/main/java/com/sejong/sejongpeer/security/constant/HeaderConstant.java
src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java
src/main/java/com/sejong/sejongpeer/security/util/JwtProvider.java
src/main/resources/application-datasource.yml

- #19 
- JWT 인증/인가 추가
- 관련 메소드 리팩토링
- 
-

:sparkles: JWT 인증 추가 및 관련 메소드 리팩토링

---

build.gradle
src/main/java/com/sejong/sejongpeer/global/config/QuerydslConfig.java

- close #24
- Querydsl 활성화
- 실행 전 어노테이션 처리 활성화 enable 해주세요~
-

✨ feat: Querydsl 활성화

---

docker/docker-compose.blue.yml
docker/docker-compose.green.yml
src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java

- #31 
- 커밋을 잘못 적었습니다.. 이 점 참고해주시면 감사하겠습니다
- 
-

:gear: docker yml 포트포워딩 임시 변경

---

src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
src/main/java/com/sejong/sejongpeer/domain/member/dto/request/SignUpRequest.java
src/main/java/com/sejong/sejongpeer/domain/member/dto/response/MemberInfoResponse.java
src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java
src/main/resources/application-security.yml
src/test/java/com/sejong/sejongpeer/domain/member/repository/MemberRepositoryTest.java
src/test/java/com/sejong/sejongpeer/domain/member/service/MemberServiceTest.java

♻️ 멤버 API 리팩토링

---

src/main/java/com/sejong/sejongpeer/domain/buddy/entity/Buddy.java

- close #49 
-  Buddy 엔티티에 MySQL 예약어와 겹쳐 에러 발생한 부분 수정했습니다.
- 
-

:bug: MySQL 예약어 중복에러 수정

---

.github/workflows/build.yml
build.gradle
config/checkstyle/naver-checkstyle-rules.xml
config/checkstyle/naver-checkstyle-suppressions.xml
src/main/java/com/sejong/sejongpeer/domain/auth/entity/RefreshToken.java

- close #44 
- spotless 제거와 checkstyle을 적용하였습니다
- 이제 작업한 클래스 파일에 저장 버튼을 눌러 자동 포맷팅 될 것입니다.
- 그러나, spotless처럼 강력하게 포맷팅되지 않아 조금이라도 가독성 있는 개발 부탁드려용 
- https://hello-judy-world.tistory.com/211
-

:bug: spotless 제거 및 checkstyle 적용

---

src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/MatchingStatusResponse.java
src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

- #56 
- 버디 등록 시 패널티인 유저는 버디신청을 못하도록 필터링
- 
-

♻️ 버디 추가 시 이전 패널티 확인 

---

src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java

- #52
- 버디 중도 취소 input값을 삭제
- 등록된 버디가 없을때 중도취소 요청 시 예외처리
- 
-

♻️ 버디 중도취소 input값 삭제 및 등록된 버디가 없을 때 취소 예외처리

---

src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/MatchingService.java

:sparkles: 버디 등록 시, 짝 찾기 실행

---

src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/MatchingService.java

🐛 상태에 따른 버디 조회 메소드 수정

---

src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java

- close #74 
- 버디 짝매칭이 성사되었을 경우 문자 보내는 기능 구현입니다. 
- 
-

✨ 버디 짝매칭 성공 시 문자 발송 기능 추가

---

src/main/java/com/sejong/sejongpeer/domain/buddy/service/MatchingService.java
src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/Honbab.java
src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/type/GenderOption.java
src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/type/HonbabStatus.java
src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/type/MenuCategoryOption.java
src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbabmatched/HonbabMatched.java
src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbabmatched/type/HonbabMatchedStatus.java
src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabMatchedRepository.java
src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabRepository.java
src/main/java/com/sejong/sejongpeer/domain/honbab/scheduler/HonbabMatchingScheduler.java
src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabMatchingService.java
src/main/java/com/sejong/sejongpeer/domain/honbab/util/HonbabFilter.java
src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java
src/main/resources/application-dev.yml

- #69 
- 
- 혼밥 등록 시, `matchHonbab(Honbab me)` 메소드 호출하여 최초 매칭 실행시켜주시면 됩니다.
-

✨ 혼밥 엔티티 구성 및 매칭 기능 구현

---

src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java

:recycle: 등록된 버디가 없을 때 상대정보 요청시 null 리턴

---

src/main/java/com/sejong/sejongpeer/domain/honbab/dto/request/RegisterHonbabRequest.java
src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbab/Honbab.java
src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabRepository.java
src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabMatchingService.java

- close #90 
- 대기 시간을 선택 받는 것이 아니라 15분 동안 혼밥 매칭 스케쥴링을 통해 짝꿍을 찾다가 매칭이 안되면 TIME_OUT 처리
-

✨ 혼밥 매칭 시 정해진 대기 시간이 지났을 경우 매칭 TIME_OUT

---

src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java

- close #95 
- @RequestBody 어노테이션이 swagger랑 겹쳐서 발생한 오류수정
- 
-

:bug: Request 어노테이션 수정

---

src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java

✨ 혼밥 등록 시 혼밥 매칭 스케쥴러 실행

---

src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
src/main/java/com/sejong/sejongpeer/global/common/constants/SwaggerUrlConstants.java
src/main/java/com/sejong/sejongpeer/global/common/constants/UrlConstants.java
src/main/java/com/sejong/sejongpeer/global/config/swagger/SwaggerConfig.java
src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java

RefreshToken 검증 임시 중지

---

src/main/resources/application-prod.yml
src/main/resources/application.yml

- #91 
- DB 스키마만 검증하도록 변경하였습니다. (ddl-auto create -> validate)
- dev 환경과 다르게 logging 설정 하였습니다
- 
-

:gear: prod yml 생성

---

src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddymatched/BuddyMatched.java
src/main/java/com/sejong/sejongpeer/domain/honbab/entity/honbabmatched/HonbabMatched.java

:bug: HonbabMatched, BuddyMatched BaseAuditEntity 상속

---

src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
src/main/java/com/sejong/sejongpeer/domain/member/dto/request/SignUpRequest.java
src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
src/test/java/com/sejong/sejongpeer/domain/member/api/MemberControllerTest.java

🐛 request DTO validation 수정

---

src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
src/main/java/com/sejong/sejongpeer/domain/auth/dto/request/TokenReissueRequest.java
src/main/java/com/sejong/sejongpeer/domain/auth/dto/response/TokenReissueResponse.java
src/main/java/com/sejong/sejongpeer/domain/auth/entity/RefreshToken.java
src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java

- #101 
- 
- 프론트에서도 추가 작업이 필요한 부분이므로 협의 후 merge하겠습니다
-

♻️ Access Toekn 재발급 방식 변경

---

src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
src/main/java/com/sejong/sejongpeer/domain/auth/dto/request/TokenReissueRequest.java
src/main/java/com/sejong/sejongpeer/domain/auth/dto/response/TokenReissueResponse.java
src/main/java/com/sejong/sejongpeer/domain/auth/entity/RefreshToken.java
src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java

Reverts SejongPeer/SejongPeer-back#104

Revert "♻️ Access Toekn 재발급 방식 변경"

---

src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

✨혼밥 신청 후 중도 취소 기능

---

src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/ActiveCustomersCountResponse.java
src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
src/main/java/com/sejong/sejongpeer/domain/honbab/repository/HonbabRepository.java
src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java

- close #115
- BuddyRepository에서 안쓰는 함수 삭제
- 
-

✨ 버디 신청인원수, 혼밥 신청인원수 리턴 기능 

---

src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java

- #110 
- refresh token 최초 검증은 제외하였습니다.
- 
-

🐛 refresh token이 유효할 시, access token 재설정하는 로직 복구

---

src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java

- close #119 
- 혼밥 매칭 이후 시간 제한 추가 반영하여 문자 발송 내역도 변경
- 15분 이후에는 상태가 in progress가 아니라면 시간 제한 없이 혼밥 신청 가능
- 
-

✨ 혼밥 밥짝꿍 매칭 이후 15분 동안 혼밥 신청 금지

---

src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java

- close #121 
- 계정 2개를 만들어 버디를 매칭시키고 postman으로 분기를 고려한 모든 상황에 대해 코드 작성 및 테스트 완료했습니다
- 
-

🐛 버디 짝매칭 이후 수락/거절 로직 문제 개선 및 해결

---

src/main/java/com/sejong/sejongpeer/domain/auth/api/AuthController.java
src/main/java/com/sejong/sejongpeer/domain/auth/dto/request/SejongAuthRequest.java
src/main/java/com/sejong/sejongpeer/domain/auth/dto/response/SejongAuthClientResponse.java
src/main/java/com/sejong/sejongpeer/domain/auth/dto/response/SejongAuthResponse.java
src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
src/main/java/com/sejong/sejongpeer/global/config/WebClientConfig.java
src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java

- close #125 
- Sejong auth 외부 API 호출
- WebClient Config를 사용하여 호출하였습니다.
- 
-

✨ Sejong auth webClient 추가

---

src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java

- close #130 
- 버디 매칭 이후 거절한 유저에게 패널티 안내 문자 전송
- 
-

✨ 버디 매칭 거절 시 거절한 유저에게 패널티 문자 전송 기능 추가

---

src/main/java/com/sejong/sejongpeer/domain/buddy/constant/LimitTimeConstant.java

- close #132 
- 버디 거절 패널티 24시간 -> 1시간 
- 
-

:art: 24시간 패널티 -> 1시간 패널티

---

src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java

- close #126 
- 재등록 시간확인, 진행중인 혼밥이 있는지 체크하는 코드 함수로 빼기
- 
-

♻️ 혼밥 service 구조 리펙토링

---

src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

🐛 ErrorCode 수정

---

src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

- close #138 
- 쿼리로 해당 member의 Buddy 상태값이 MATCHING_COMPLETED인 Buddy 수를 가지고 버디 등록시 3회까지 제한
- 
-

✨ 버디 등록 3회 제한 기능 

---

.github/workflows/staging_deploy.yml
appspec-staging.yml
scripts/staging_deploy.sh

- close #144 
- develop 브랜치 push, pull_request
- 
-

⚙️ develop 스테이징 서버 배포 

---

src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyRepository.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java

- close #129 
- 쿼리 최적화
- postman으로 기능 구현 상에 문제 없음을 확인했습니다
-

♻️ 버디 짝매칭 이후 수락/거절 로직 쿼리 최적화 리팩토링

---

.github/workflows/staging_deploy.yml

- close #151 
- develop에 병합 할 때만 빌드해서 자동배포 되도록 수정
- 
-

:green_heart: develop브랜치에 push시에만 action실행

---

.github/workflows/build.yml

:green_heart: develop 2번 빌드되는거 수정

---

src/main/java/com/sejong/sejongpeer/domain/buddy/repository/BuddyMatchedRepository.java
src/main/java/com/sejong/sejongpeer/domain/buddy/scheduler/MatchingScheduler.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java

- close #160 
- @rong5026 추가적으로 피드백 주신 부분에 대한 수정 사항입니다!
- postman test 완료했습니다
-

♻️ 버디 수락/거절 및 자동 거절 처리 스케쥴러 BuddyMatched 찾는 방식 변경

---

src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/ActiveCustomersCountResponse.java
src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/CompletedPartnerInfoResponse.java
src/main/java/com/sejong/sejongpeer/domain/buddy/dto/response/MatchingStatusResponse.java
src/main/java/com/sejong/sejongpeer/domain/buddy/entity/buddy/Buddy.java
src/main/java/com/sejong/sejongpeer/domain/buddy/scheduler/MatchingScheduler.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
src/main/java/com/sejong/sejongpeer/domain/honbab/dto/response/HonbabMatchingStatusResponse.java
src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabMatchingService.java
src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
src/main/java/com/sejong/sejongpeer/domain/member/dto/response/ExistsCheckResponse.java
src/main/java/com/sejong/sejongpeer/domain/member/dto/response/MemberInfoResponse.java
src/main/java/com/sejong/sejongpeer/domain/member/repository/MemberRepository.java
src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

- close #168 
- 기존 Buddy, BuddyMatching, Honbab, HonbabMatching 등 서비스 코드 개선
- 
-

♻️ 서비스 코드 개선

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/staging_deploy.yml
build.gradle
src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java
src/main/java/com/sejong/sejongpeer/security/filter/JwtAuthenticationFilter.java
src/main/resources/application-actuator.yml
src/main/resources/application.yml

- close #186 
- health 체크를 위한 Spring Actuator를 구현하였습니다.
- 사용 용도로는 그라파나/프로메테우스, Load Balancing 정도 있을 거 같네요
- 
-

⚙️ Spring Actuator 구성

---

build.gradle
src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyMatchingService.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java
src/main/java/com/sejong/sejongpeer/domain/college/entity/CollegeMajor.java
src/main/java/com/sejong/sejongpeer/domain/college/service/CollegeMajorService.java
src/main/java/com/sejong/sejongpeer/domain/externalactivitystudy/entity/ExternalActivity.java
src/main/java/com/sejong/sejongpeer/domain/externalactivitystudy/entity/ExternalActivityStudy.java
src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java
src/main/java/com/sejong/sejongpeer/domain/image/api/ImageController.java
src/main/java/com/sejong/sejongpeer/domain/image/service/ImageService.java
src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/Lecture.java
src/main/java/com/sejong/sejongpeer/domain/lecturestudy/entity/LectureStudy.java
src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
src/main/java/com/sejong/sejongpeer/global/util/MemberUtil.java
src/main/java/com/sejong/sejongpeer/global/util/SecurityUtil.java
src/main/java/com/sejong/sejongpeer/security/MemberDetails.java
src/test/java/com/sejong/sejongpeer/domain/member/service/MemberServiceTest.java
src/test/java/com/sejong/sejongpeer/util/MemberUtilTest.java

- close #170 
- SecurityContext 호출하는 영역을 분리하여 Service 단에서 호출하도록 변경
- PR Approve 완료 시 기존 String memberId 주석된 부분은 제거할 예정입니다
-

✨ MemberUtil 구현

---

src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
src/main/java/com/sejong/sejongpeer/domain/lecturestudy/controller/LectureController.java
src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java

- close #196 
- API Swagger Tag 넘버링 수정 
- 
-

:bug: `@Tag` 넘버링 수정

---

src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
src/main/java/com/sejong/sejongpeer/domain/scrap/dao/ScrapRepository.java
src/main/java/com/sejong/sejongpeer/domain/scrap/dto/request/StudyScrapCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/scrap/dto/response/StudyScrapResponse.java
src/main/java/com/sejong/sejongpeer/domain/scrap/entity/Scrap.java
src/main/java/com/sejong/sejongpeer/domain/scrap/entity/ScrapType.java
src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

- close #193 
- 다대다 Scrap 테이블 조인으로 중간 테이블을 두어 해결
- 
-

✨ 스터디 스크랩 기능

---

src/main/java/com/sejong/sejongpeer/domain/honbab/api/HonbabController.java
src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabMatchingService.java
src/main/java/com/sejong/sejongpeer/domain/honbab/service/HonbabService.java

- close #201 
- TIME_OUT 상태 변경 시간 조건을 15분에서 24시간으로 변경
- active-count 혼밥 매칭 상대 찾는 IN_PROGRESS 상태 count 반환에서 전체 이용자 수 반환으로 변경
- 
-

✨축제 기간 혼밥 탈출 기능 변경

---

build.gradle
src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/dto/request/StudyApplyRequest.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/dto/response/StudyRelationCreateResponse.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/entity/StudyRelation.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

- close #204 
- close #205 
- 스터디 지원 구현 및 이미 지원한 이력이 있으면 예외 처리
- 지원자 수는 accept status를 count한 값을 반환
- 이미지는 mock data를 insert하여 study 테이블의 img_url 값을 반환
- 
-

✨ 스터디 지원 및 게시글 별 지원자 수 현황 추가

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/entity/StudyRelation.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java
src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java

스터디 조기마감 병합

---

src/main/java/com/sejong/sejongpeer/domain/college/api/CollegeMajorController.java
src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
src/main/java/com/sejong/sejongpeer/global/config/swagger/SwaggerConfig.java

- close #218 
- 스웨거 권한 문제에 대해 프론트에서 테스트 가능하도록 swaggerConfig 수정
- 프론트에서 두 종류 토큰 둘다 Bearer 붙이지 않아도 됨
-

🐛 Swagger 상에서 access token, refresh token 넣고 request, response 확인 가능하도록 수정

---

src/main/java/com/sejong/sejongpeer/domain/externalactivity/entity/ExternalActivity.java
src/main/java/com/sejong/sejongpeer/domain/study/api/ExternalActivityStudyController.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
src/main/java/com/sejong/sejongpeer/domain/study/entity/type/Frequency.java
src/main/java/com/sejong/sejongpeer/domain/study/entity/type/StudyMethod.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
src/main/java/com/sejong/sejongpeer/domain/study/vo/StudyVo.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java

- close #
- 스터디 생성 기능 추가
- 아직 태그 로직은 추가하지 못했습니다.
-

게시글 생성 및 Study 엔티티 수정 병합

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
src/main/java/com/sejong/sejongpeer/domain/study/entity/StudyTagMap.java
src/main/java/com/sejong/sejongpeer/domain/study/entity/Tag.java
src/main/java/com/sejong/sejongpeer/domain/study/repository/StudyTagMapRepository.java
src/main/java/com/sejong/sejongpeer/domain/study/repository/TagRepository.java
src/main/java/com/sejong/sejongpeer/domain/study/service/ExternalActivityStudyService.java
src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java
src/main/java/com/sejong/sejongpeer/domain/study/service/TagService.java
src/main/java/com/sejong/sejongpeer/domain/study/vo/StudyVo.java

- close #
- 게시물 태그 기능 추가
- 게시물 - 중간테이블 - 태그
- 나중에 태그에 대한 게시글 수, 검색 기능 생각해서 중간테이블 넣어서 1대 다 관계로 제작
- 메서드 분리, 리펙토링 후에 필요함
-

:sparkles: 태그 기능 추가

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java

:sparkles: 임시로 request에 image 리스트 받기

---

.github/workflows/deploy.yml
gradle/wrapper/gradle-wrapper.properties

- close #233 
- close #234 
- 이미지 base64 인코딩 request 로직 main으로 배포 안되는 오류 해결
- 스웨거 상에 base64 이미지 처리 api는 배포 된 상황
-

Feature/#230 -> main으로 배포 안되는 이슈 해결

---

src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
src/main/java/com/sejong/sejongpeer/domain/study/service/TagService.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/dto/response/AppliedStudyResponse.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

develop main 병합

---

src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
src/main/java/com/sejong/sejongpeer/domain/scrap/dao/ScrapRepository.java
src/main/java/com/sejong/sejongpeer/domain/scrap/dto/request/StudyScrapCountRequest.java
src/main/java/com/sejong/sejongpeer/domain/scrap/dto/response/StudyScrapCountResponse.java
src/main/java/com/sejong/sejongpeer/domain/study/api/LectureStudyController.java
src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java

- close #237 
- 프론트에서 게시글 전체 조회 및 상세 조회 시 해댱 API 연결해야 함
- 게시글 전체 조회를 무한 스크롤로 구현했기 때문에 쓰지 않는 이전 버전의 게시글 목록 조회 API 주석 처리
- 200 ok 확인

✨ 게시글 별 스크랩 수 조회

---

src/main/java/com/sejong/sejongpeer/domain/study/repository/StudyRepository.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java

- close #253 
- 업데이트할 Study 찾을 때 member와 studyid 동시에 검색
- 
-

:sparkles: 스터디 수정 시 게시자만 수정가능

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/service/ExternalActivityStudyService.java
src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

- close 
- Member utils 부분 final 처리
- 대외, 교내 스터디 생성 request @Notnull처리
- 
-

:sparkles: 스터디 Service Security 호출 부분 final

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/request/ExternalActivityStudyCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/request/LectureStudyCreateRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/service/ExternalActivityStudyService.java
src/main/java/com/sejong/sejongpeer/domain/study/service/LectureStudyService.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

MemberUtil 부분 final 처리

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

- close #261 
- 
- 
- DB studyRelation 스터디 신청 현황을 저장한 테이블이 초기화 되면서 예외 처리 생각해야 할 부분 추가 고려

🐛 스터디 지원 404 bad request

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java

- close #263
- 
- 
- 200 ok 확인

♻️ 게시글 무한스크롤 전체 조회, 게시글 상세 조회, 게시글 검색 response에 게시글 별 스크랩 수 함께 반환

---

src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsText.java

✨ 지원자 있을 경우, 스터디 삭제되었을 경우, 지원 거절당했을 경우 문자 발송

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java

- close #266 
- 상세 조회 시 -> 전달 링크, 문의 링크 둘다
- 상세 조회 및 전체 조회(무한스크롤, 검색) -> 스터디 게시글 List<String> tags 추가
- 
-

✨StudyPostInfoResponse, StudyTotalPostResonse DTO data 추가

---

src/main/java/com/sejong/sejongpeer/domain/image/api/ImageController.java
src/main/java/com/sejong/sejongpeer/domain/image/repository/ImageRepository.java
src/main/java/com/sejong/sejongpeer/domain/image/service/ImageService.java

- close #268 
- 게시글 수정 시 이미지도 변경될 경우 기존 이미지 등록 api를 그대로 연결하여 reset
- 
- 200 ok 이미지 url 변경 사항 db 확인 완료

✨ 게시글 이미지 수정

---

src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
src/main/java/com/sejong/sejongpeer/domain/scrap/dao/ScrapRepository.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java

- close #273
- 
- 
- 백엔드는 역할 재분배 이후 세종스터디 큼지막한 기능 구현 완료

✨ 마이페이지 내가 좋아요한 글 목록 전체 조회

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostResponse.java

✨ 게시글 목록 조회 공용 response 필드 추가

---

src/main/java/com/sejong/sejongpeer/domain/image/api/ImageController.java
src/main/java/com/sejong/sejongpeer/domain/image/service/ImageService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

⚡ 백에서 S3 업로드 로직 개선

---

src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java

- close #279 
- final 추가
- 공용 dto 반환 로직 메소드화
- stream method reference 
- 
-

♻️ 세종스터디 코드 리펙토링

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
src/main/java/com/sejong/sejongpeer/infra/sms/service/SmsService.java

🐛 스터디 지원 거절 처리 문자 발송 Enum IllegalArgumentException 해결

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java

♻️ 스터디 조기 마감 엔드포인트 수정

---

src/main/java/com/sejong/sejongpeer/domain/study/entity/Study.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

✨ 스터디 조기마감 시 스터디 게시글 모집 상태 변경

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

- close #290
- 해당 스터디를 만든 사람이 조기마감 가능하도록 기능 추가
- 신청자가 없더라도 마감할 수 있도록 수정
- 
-

:sparkles: 스터디 조기마감 시 신청내역이 없어도 조기마감 가능기능 추가

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyApplicantsListRespone.java

- close #292 
- 피그마 수정사항에 따른 프론트에서 필요한 데이터 추가
- 
-

✨ 스터디 지원자 조회 모집 인원, 수락 인원 응답 추가

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

- close #294 
- 스터디 조기마감 요청 시 이미 마감된 스터디라면 409 conflict 에러 리턴
- 
-

:sparkles: 스터디 조기마감 시 이미 마감된 스터디 예외처리

---

src/main/java/com/sejong/sejongpeer/domain/buddy/api/BuddyController.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyManagementFacade.java
src/main/java/com/sejong/sejongpeer/domain/buddy/service/BuddyService.java

♻️ 세종버디 facade class가 총괄 하도록 구현 및 여러 서비스 코드 의존성 제거

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

- close #298 
- 조기마감 메시지 전송 시 ENUM에러
- 
-

:bug: 카카오톡 링크 전송 오류 수정

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyApplicantsListRespone.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

- close #302 
- 취소된 사람 빼고 리턴
- 
-

:sparkles: 스터디 지원자 리스트 중 PENDING, ACCEPT, REJECT 지원자만 리턴

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyApplicantsListRespone.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

- close #
- 스터디 지원자 리스트 조회 중 REJECT한 사용자 제외하고 리턴
- 
-

스터디 지원자 조건 수정

---

src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
src/main/resources/application-security.yml

- close #305
- 지원자 리스트 리턴시에 lecture, external 분리해서 리턴
- 
-

:sparkles: 스터디 타입에 따른 지원자 리스트 리턴

---

src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
src/main/resources/application-security.yml

스터디 타입에 따라 지원자 리스트 반환

---

src/main/java/com/sejong/sejongpeer/domain/member/api/MemberController.java
src/main/java/com/sejong/sejongpeer/domain/member/entity/Member.java
src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
src/main/java/com/sejong/sejongpeer/domain/member/service/MemberVerificationService.java

♻️ 회원 Service Layer 분리

---

src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/dto/response/AppliedStudyResponse.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

:sparkles: 지원한 스터디 정보 스크랩 수 포함 후 리턴

---

.github/workflows/deploy.yml
build.gradle
src/main/java/com/sejong/sejongpeer/SejongpeerApplication.java
src/main/java/com/sejong/sejongpeer/domain/auth/entity/RefreshToken.java
src/main/java/com/sejong/sejongpeer/domain/auth/repository/RefreshTokenRepository.java
src/main/java/com/sejong/sejongpeer/domain/auth/service/AuthService.java
src/main/java/com/sejong/sejongpeer/domain/college/service/CollegeMajorService.java
src/main/java/com/sejong/sejongpeer/domain/externalactivity/service/ExternalActivityService.java
src/main/java/com/sejong/sejongpeer/global/config/CacheConfig.java
src/main/java/com/sejong/sejongpeer/global/config/RedisConfig.java
src/main/java/com/sejong/sejongpeer/infra/config/properties/PropertiesConfig.java
src/main/java/com/sejong/sejongpeer/infra/config/properties/RedisProperties.java
src/main/resources/application-redis.yml
src/main/resources/application.yml

- close #312 
- close #314 
- 이미 deploy.yml에서 push할 때 `refactor/#312 `branch를 추가했기 때문에 운영 서버에 배포가 된 상황
- 프론트에서도 로그인 200 ok 확인 완료
- nginx 502 gateway 문제 해결 완료 -> 서버 코드 문제가 아니었음
- 
-

✨AWS ElastiCache Redis 구축

---

.github/workflows/deploy.yml
src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyPostSearchRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudySpecification.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
src/main/java/com/sejong/sejongpeer/global/config/CacheConfig.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

- close #318
- 
- 검색 스크롤할 때 int page++ 요청 시 서로 다른 게시글들을 반환하고 data 응답 값이 null이면 마지막 페이지
-

♻️ 게시글 검색 Nullable 필터링 가능하도록 수정

---

src/main/java/com/sejong/sejongpeer/domain/study/api/StudyController.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/request/StudyPostSearchRequest.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java

- close #321 
- 아래와 같이 param으로 받도록 수정
- 
-

🐛 게시글 필터링 조건 쿼리스트링으로 받도록 통일

---

src/main/java/com/sejong/sejongpeer/domain/study/service/StudySpecification.java

🐛 게시글 검색어 Null 처리 추가

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

- close #328 
- 메세지 전송 메서드에서 subString(0,10) 부분 길이 비교 후 Excetion 처리
- 
-

:bug: 제목이 10자 미만일 경우 Exception Error 수정

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

🐛 스터디 지원자 수락 시 모집 인원까지만 받도록 예외 처리 추가

---

src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java

- close #335 
- QA 반영
- 
- 200 확인

✨ 로그인한 유저의 스터디 게시글 별 지원 여부 반환 추가

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

♻️ 세종스터디 마이페이지 내가 작성한, 내가 지원한 목록에 대해 역순 정렬

---

.github/workflows/deploy.yml
docker/Dockerfile
docker/docker-compose.blue.yml
docker/docker-compose.green.yml
scripts/deploy.sh

- close #320
- 기존에 도커로 배포 안되는 상황 해결
- 블루 그린 번갈아 실행되는 것까지 모두 확인
- 
- fix/#320을 deploy.yml에 추가하여 이미 배포되고 실행되고 있는 상태

🐛 도커컴포즈 블루그린 무중단 배포 최종 완료

---

src/main/java/com/sejong/sejongpeer/domain/scrap/dao/ScrapRepository.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoResponse.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java

✨ 게시글 상세 조회 유저의 해당 게시글 스크랩 여부 추가

---

src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
src/main/java/com/sejong/sejongpeer/domain/scrap/dto/response/StudyScrapCreateResponse.java

♻️ 스터디 스크랩 추가 시 scrapId 명시적으로 반환

---

src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/repository/StudyRelationRepository.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

✨ 스터디 모집 인원 다 찼을 경우 모집 마감 문자 발송

---

src/main/java/com/sejong/sejongpeer/domain/study/service/StudyService.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

🐛 스터디 게시글 제목 substring exception 처리

---

src/main/java/com/sejong/sejongpeer/domain/scrap/api/ScrapController.java
src/main/java/com/sejong/sejongpeer/domain/scrap/application/ScrapService.java
src/main/java/com/sejong/sejongpeer/domain/scrap/dao/ScrapRepository.java
src/main/java/com/sejong/sejongpeer/global/error/exception/ErrorCode.java

♻️ 스크랩 삭제 시 scrapId 사용 안하는 로직으로 대체

---

.github/workflows/deploy.yml
docker/Dockerfile

⚙️ 운영서버 prod 프로필 활성화

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

:zap: 수락 거절 수 지원가능 여부 응답값 리턴

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/api/StudyRelationController.java
src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java
src/main/resources/application.yml

스터디 수락 거절 응답 생성

---

src/main/java/com/sejong/sejongpeer/domain/studyrelation/service/StudyRelationService.java

Feature/#357 수락 거절 응답값 변경

---

src/main/java/com/sejong/sejongpeer/domain/study/api/StudyNoLoginController.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyPostInfoNoLoginResponse.java
src/main/java/com/sejong/sejongpeer/domain/study/dto/response/StudyTotalPostNoLoginResponse.java
src/main/java/com/sejong/sejongpeer/domain/study/service/StudyNoLoginService.java
src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java

- close #362 
- 
- 
- 전체 조회 및 상세 조회 둘 다 200 확인 완료

✨ 비로그인 유저도 게시글 전체 목록 조회 및 상세 조회 가능하도록 추가

---

src/main/java/com/sejong/sejongpeer/domain/member/dto/request/MemberUpdateRequest.java
src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java

회원정보 request. 값 추가, swagger cors 처리

---

src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java

:bug: swagger에서 요청시 cors 적용

---

src/main/java/com/sejong/sejongpeer/domain/member/service/MemberService.java
src/main/java/com/sejong/sejongpeer/domain/member/service/MemberVerificationService.java

:sparkles: 회원정보 수정에서 본인 정보에서 값이 수정된 값이 있을 때만 중복 검사 ( 함수형 인터페이스 사용 )

---

src/main/java/com/sejong/sejongpeer/security/config/WebSecurityConfig.java
src/main/java/com/sejong/sejongpeer/security/constant/WebSecurityURIs.java

- close #
- 회원정보 중 수정된 값만 중복체크 후 예외처리
- 
- 
-

회원정보 수정 시 중복체크 로직 변경
